[connections.default]
account = "override-via-env"
user = "override-via-env"
authenticator = "SNOWFLAKE_JWT"
private_key_file = "/tmp/rsa_key.p8"
warehouse = "SNOWADHOC"
role = "DEVREL_ADMIN_RL"
database = "DEVREL"
schema = "CNANTASENAMAT_DEV"
